on: [push]

jobs:
  soos_dast_baseline_analysis:
    name: SOOS DAST Baseline Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Run SOOS DAST Baseline Analysis
        uses: soos-io/soos-dast-github-action@feature/PA-11731 # GET Latest Version from https://github.com/marketplace/actions/soos-dast
        with:

          client_id: ${{ secrets.SOOS_CLIENT_ID }}
          api_key: ${{ secrets.SOOS_API_KEY }}
          project_name: 'GH-Actions-DAST-multi-page' 
          auth_form_type: 'multi_page'
          target_url: 
          api_url: 'https://qa-api.soos.io/api/'          
          auth_login_url: 'https://login.yahoo.com/'                  
          auth_username: 'franco.juarez08@yahoo.com'        
          auth_password: 'Micring00'        
          auth_username_field: 'login-username'        
          auth_password_field: 'login-passwd'          
          auth_submit_field: 'login-signin'          
          auth_second_submit_field: 'login-signin'

